spring.application.name=ecoflights

spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/ecoflights
spring.datasource.password=20062004

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080

google.api.key=AIzaSyDKzcoMmzB5JHVrZl0jYbR_Dp2_sIp0JY8

api.serp.base-url=https://api.serpapi.com
api.serp.api-key=98e59317bac49dd8c6791da7bf3a4cd6ef7318f7bfaab18d07d4a6597389fb53
